# Generated by Django 3.0.8 on 2020-07-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='items',
            field=models.TextField(default='1', verbose_name='Hi'),
        ),
    ]
