# Generated by Django 3.0.8 on 2020-07-05 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orderitem_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='items',
        ),
    ]
